# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: unit-tests

on:
  push:
    branches:
    - dev
    - canary/*
    - release/*
  pull_request:
    branches:
    - dev
    - canary/*
    - release/*
  release:
    types:
    - published

jobs:
  nvidia-h200-1n8g:
    name: nvidia-h200-1n8g
    runs-on: unit-tests
    timeout-minutes: 120
    permissions:
      contents: read
    strategy:
      fail-fast: true
    steps:
      - name: Checkout target branch
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Test target branch
        run: |
          bash ${LTP_RUN_CI_SCRIPT_PATH} unit-tests-nvidia-h200-1n8g
  amd-mi300x-1n8g:
    name: amd-mi300x-1n8g
    runs-on: unit-tests
    timeout-minutes: 120
    permissions:
      contents: read
    strategy:
      fail-fast: true
    steps:
      - name: Checkout target branch
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Test target branch
        run: |
          bash ${LTP_RUN_CI_SCRIPT_PATH} unit-tests-amd-mi300x-1n8g
