name: unit-tests

on:
  push:
    branches:
    - dev
    - canary/*
    - release/*
  pull_request:
    branches:
    - dev
    - canary/*
    - release/*
  release:
    types:
    - published

jobs:
  single-rank-amd-mi300x:
    name: single-rank-amd-mi300x
    runs-on: unit-tests
    timeout-minutes: 3600
    permissions:
      contents: read
    strategy:
      fail-fast: true
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
      - name: Test target branch
        run: |
          bash ${LTP_RESOURCES_DIR}/run_unit_tests_single_rank_amd_mi300x_proxy.sh
